spring:
  application:
    name: auth-server
  security:
    oauth2:
      authorizationserver:
        client:
          sfg-client:
            registration:
              client-id: "sfg-client"
              client-secret: "{noop}sfg-secret"
              client-authentication-methods:
                - "client_secret_basic"
                - "client_secret_post"
              authorization-grant-types:
              - "client_credentials"
              - "authorization_code"
              - "refresh_token"
              scopes:
              - "read"
              - "write"
              redirect-uris:
                - "http://${GATEWAY_SERVER:127.0.0.1}:${GATEWAY_SERVER_PORT:8080}/login/oauth2/code/messaging-client-oidc"
                - "http://${GATEWAY_SERVER:127.0.0.1}:${GATEWAY_SERVER_PORT:8080}/authorized"
              post-logout-redirect-uris:
                  - "http://${GATEWAY_SERVER:127.0.0.1}:${GATEWAY_SERVER_PORT:8080}/logged-out"
            require-authorization-consent: true
server:
  port: 9000

